# This is a basic workflow to help you get started with Actions

name: Launch Test

# Controls when the action will run. 
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    
    strategy:
      matrix:
        julia-version: ["1.0", "^1.6.0-0"]
        os: [windows-latest, ubuntu-latest]
        
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: Test launch Pluto
        run: | 
          echo "hello world" 
          julia ${{ github.workspace ]}/test/run_notebook.jl ${{ github.workspace }}
