# This is a basic workflow to help you get started with Actions

name: Pluto CI test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    
    # Ensure one failed test doesn't halt CI
    continue-on-error: true
    
    strategy:
      matrix:
        julia-version: ["1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "1.6"]
        os: [ubuntu-latest]
        include:
          - julia-version: "1.0"
            os: macOS-latest
          - julia-version: "^1.6.0-0"
            os: macOS-latest
          - julia-version: "1.0"
            os: windows-latest
          - julia-version: "^1.6.0-0"
            os: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-runtest@v1
